pipeline{
    agent any

    tools{
        nodejs "node"
    }
    parameters{
        string(name: 'container_name', defaultValue: 'pagina_web', description: 'Nombre del contenedor')
        string(name: 'image_name', defaultValue: 'pagina_img', description: 'Nombre de la imagen')
        string(name: 'image_tag', defaultValue: 'latest', description: 'Tag de la imagen')
        string(name: 'dockerfile', defaultValue: 'Dockerfile', description: 'Nombre del dockerfile')
    }
    stages{
        stage('install'){
            steps{
                git branch: 'master', url: 'https://github.com/SharonBarrial/front.git'
                dir('front'){
                    sh 'npm install'
                }
            
            }
        }
        stage('test'){
            steps{
                dir('front'){
                    sh 'npm run test'
                }
            }
        }
        stage('Build'){
            steps {
               dir('frontend') {
                  script {
                    try {
                      sh 'docker stop ${container_name}'
                      sh 'docker rm ${container_name}'
                      sh 'docker rmi ${image_name}:${tag_image}'
                    } catch (Exception e) {
                      echo 'Exception occurred: ' + e.toString()
                    }
                }
                sh 'npm run build'
                sh 'docker build -t ${image_name}:${tag_image} .'
            }
          }
        }
        
        stage('Deploy'){
            steps{
                sh 'npm run deploy'
            }
        }
    }
}
