pipeline{
    agent any

    tools{
        nodejs "node"
    }

    stages{
        stage('Install'){
            steps{
                git branch: 'master', url: 'https://github.com/SharonBarrial/front.git'
                dir('front'){
                    sh 'npm install'
                }
            
            }
        }
        stage('Build'){
            steps{
                sh 'npm install'
            }
        }
        stage('Test'){
            steps{
                dir('front'){
                    sh 'npm run test'
                }
            }
        }
        stage('Deploy'){
            steps{
                sh 'npm run deploy'
            }
        }
    }
}
